apiVersion: integration/v1
kind: Step
name: vault-step-run-command
version: 3
summary: Run command
description: |
  This step runs Vault CLI commands against a vault server.
icon:
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/vault-step-run-command
schemas:
  spec:
    source: file
    file: spec.schema.json
